# Generated by Django 6.0.5 on 2026-05-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/')),
                ('bio_text', models.TextField(help_text='u can arrange the text abt me')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
