# Generated by Django 6.0.5 on 2026-05-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence & ML'), ('BE', 'Backend Development'), ('FE', 'Frontend Development'), ('DB', 'Database Management'), ('LG', 'Languages'), ('OT', 'Other Tools')], default='BE', max_length=2),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(help_text='e.g፦ fab fa-python', max_length=100),
        ),
    ]
