# Generated by Django 6.0.5 on 2026-05-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_skill_category_alter_skill_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issued_by', models.CharField(help_text='ለምሳሌ፦ Google, Coursera, Udemy', max_length=200)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('description', models.TextField(blank=True)),
                ('date_received', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
