# Generated by Django 6.0.5 on 2026-05-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_by',
            field=models.CharField(help_text='e.q፦ Google, Coursera, Udemy', max_length=200),
        ),
    ]
